config/routes.rb
Rails.application.routes.draw do
  resources :stocksproducts
  resources :rifleproducts
  resources :barrelproducts
  resources :opticsproducts
  resources :photos
  resources :static_pages
  resources :webpages
  resources :preloveds
  resources :reloadings
  resources :miscellaneous
  resources :triggers
  resources :archeries
  resources :stocks
  resources :optics
  resources :barrels

  resources :dues
  resources :rifles
  resources :when_dues
  resources :makes
  resources :posts
  resources :news
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/archery.rb
class Archery < ActiveRecord::Base
  belongs_to :due
  belongs_to :make

  validates :name, presence: true
  validates :name, uniqueness: true

  has_attached_file :image, :styles => { :medium => "450x450>", :thumb => "250x250>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/models/barrel.rb
class Barrel < ActiveRecord::Base
  belongs_to :due
  belongs_to :make

  validates :name, presence: true
  validates :name, uniqueness: true

  has_attached_file :image, :styles => { :medium => "450x450>", :thumb => "250x250>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/due.rb
class Due < ActiveRecord::Base

  has_many :rifles
  has_many :archeries
  has_many :barrels
  has_many :miscellaneous
  has_many :optics
  has_many :preloveds
  has_many :reloadings
  has_many :stocks
  has_many :triggers

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/make.rb
class Make < ActiveRecord::Base
  has_many :rifles
  has_many :archeries
  has_many :barrels
  has_many :miscellaneous
  has_many :optics
  has_many :preloveds
  has_many :reloadings
  has_many :stocks
  has_many :triggers

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/miscellaneou.rb
class Miscellaneou < ActiveRecord::Base
  belongs_to :due
  belongs_to :make

  validates :name, presence: true
  validates :name, uniqueness: true

  has_attached_file :image, :styles => { :medium => "450x450>", :thumb => "250x250>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/models/news.rb
class News < ActiveRecord::Base
end

app/models/optic.rb
class Optic < ActiveRecord::Base
  belongs_to :due
  belongs_to :make

  validates :name, presence: true
  validates :name, uniqueness: true

  has_attached_file :image, :styles => { :medium => "450x450>", :thumb => "250x250>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  has_attached_file :image, :styles => { :large => "600x600", :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/preloved.rb
class Preloved < ActiveRecord::Base
  belongs_to :make

  validates :name, presence: true
  validates :name, uniqueness: true

  has_attached_file :image, :styles => { :medium => "450x450>", :thumb => "250x250>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/reloading.rb
class Reloading < ActiveRecord::Base
  belongs_to :due
  belongs_to :make

  validates :name, presence: true
  validates :name, uniqueness: true

  has_attached_file :image, :styles => { :medium => "450x450>", :thumb => "250x250>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/models/rifle.rb
class Rifle < ActiveRecord::Base

  belongs_to :make
  belongs_to :due

  validates :name, presence: true
  validates :name, uniqueness: true

  has_attached_file :image, :styles => { :medium => "450x450>", :thumb => "250x250>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  belongs_to :due
  belongs_to :make

  validates :name, presence: true
  validates :name, uniqueness: true

  has_attached_file :image, :styles => { :medium => "450x450>", :thumb => "250x250>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/models/trigger.rb
class Trigger < ActiveRecord::Base
  belongs_to :due
  belongs_to :make

  validates :name, presence: true
  validates :name, uniqueness: true

  has_attached_file :image, :styles => { :medium => "450x450>", :thumb => "250x250>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/webpage.rb
class Webpage < ActiveRecord::Base
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/when_due.rb
class WhenDue < ActiveRecord::Base

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/preloveds_controller.rb
class PrelovedsController < ApplicationController
  before_action :set_preloved, only: [:show, :edit, :update, :destroy]

  # GET /preloveds
  # GET /preloveds.json
  def index
    @preloveds = Preloved.all
  end

  # GET /preloveds/1
  # GET /preloveds/1.json
  def show
  end

  # GET /preloveds/new
  def new
    @preloved = Preloved.new
  end

  # GET /preloveds/1/edit
  def edit
  end

  # POST /preloveds
  # POST /preloveds.json
  def create
    @preloved = Preloved.new(preloved_params)

    respond_to do |format|
      if @preloved.save
        format.html { redirect_to @preloved, notice: 'Preloved was successfully created.' }
        format.json { render :show, status: :created, location: @preloved }
      else
        format.html { render :new }
        format.json { render json: @preloved.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /preloveds/1
  # PATCH/PUT /preloveds/1.json
  def update
    respond_to do |format|
      if @preloved.update(preloved_params)
        format.html { redirect_to @preloved, notice: 'Preloved was successfully updated.' }
        format.json { render :show, status: :ok, location: @preloved }
      else
        format.html { render :edit }
        format.json { render json: @preloved.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /preloveds/1
  # DELETE /preloveds/1.json
  def destroy
    @preloved.destroy
    respond_to do |format|
      format.html { redirect_to preloveds_url, notice: 'Preloved was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_preloved
      @preloved = Preloved.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def preloved_params
      params.require(:preloved).permit(:name, :model, :price, :details, :active, :make_id, :image)
    end
end

app/helpers/dues_helper.rb
module DuesHelper
end

app/helpers/makes_helper.rb
module MakesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/preloveds_helper.rb
module PrelovedsHelper
end

app/views/preloveds/_form.html.erb
<%= simple_form_for @preloved, html: {multipart: true} do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :name %>
      <%= f.input :model %>
      <%= f.association :make %>
      <%= f.input :price %>
      <%= f.input :details %>
      <%= f.input :image %>
      <%= f.input :active %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, :class => "btn btn-small btn-success" %>
    </div>
<% end %>

app/views/preloveds/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">

      <h2>Editing Pre-Loved</h2>

      <%= render 'form' %>
      <%= link_to 'Show', @preloved %> |
      <%= link_to 'Back', preloveds_path %>
    </div>
    <div class="col-md-2"></div>
  </div>
</div>

app/views/preloveds/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">

      <p id="notice"><%= notice %></p>


      <p id="notice"><%= notice %></p>

      <h2>Listing Pre-loved's</h2>

      <table class="table table-hover table-condensed">
        <thead>
        <tr>
          <th>Name</th>
          <th>Model</th>
          <th>Make</th>
          <th>Price</th>
          <th>Details</th>
          <th>Active</th>
          <th colspan="3"></th>
        </tr>
        </thead>

        <tbody>
        <% @preloveds.each do |preloved| %>
            <tr>
              <td><%= preloved.name %></td>
              <td><%= preloved.model %></td>
              <td><%= preloved.make.name %></td>
              <td><%= number_to_currency(preloved.price) %></td>
              <td><%= preloved.details %></td>
              <td><%= preloved.active %></td>
              <td><%= link_to 'Show', preloved %></td>
              <td><%= link_to 'Edit', edit_preloved_path(preloved) %></td>
              <td><%= link_to 'Destroy', preloved, method: :delete, data: {confirm: 'Are you sure?'} %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
      <br>

      <%= link_to 'New Preloved', new_preloved_path, :class => "btn btn-small btn-success" %>

    </div>
  </div>
</div>

app/views/preloveds/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">

      <h2>New Pre-Loved</h2>

      <%= render 'form' %>

      <%= link_to 'Back', preloveds_path %>
    </div>
    <div class="col-md-2"></div>
  </div>
</div>

app/views/preloveds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @preloved.name %>
</p>

<p>
  <strong>Model:</strong>
  <%= @preloved.model %>
</p>

<p>
  <strong>Price:</strong>
  <%= @preloved.price %>
</p>

<p>
  <strong>Details:</strong>
  <%= @preloved.details %>
</p>

<p>
  <strong>Active:</strong>
  <%= @preloved.active %>
</p>

<p>
  <strong>Make:</strong>
  <%= @preloved.make %>
</p>

<%= link_to 'Edit', edit_preloved_path(@preloved) %> |
<%= link_to 'Back', preloveds_path %>