config/routes.rb
Rails.application.routes.draw do
  resources :stocksproducts
  resources :rifleproducts
  resources :barrelproducts
  resources :opticsproducts
  resources :photos
  resources :static_pages
  resources :webpages
  resources :preloveds
  resources :reloadings
  resources :miscellaneous
  resources :triggers
  resources :archeries
  resources :stocks
  resources :optics
  resources :barrels

  resources :dues
  resources :rifles
  resources :when_dues
  resources :makes
  resources :posts
  resources :news
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/archery.rb
class Archery < ActiveRecord::Base
  belongs_to :due
  belongs_to :make

  validates :name, presence: true
  validates :name, uniqueness: true

  has_attached_file :image, :styles => { :medium => "450x450>", :thumb => "250x250>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/models/barrel.rb
class Barrel < ActiveRecord::Base
  belongs_to :due
  belongs_to :make

  validates :name, presence: true
  validates :name, uniqueness: true

  has_attached_file :image, :styles => { :medium => "450x450>", :thumb => "250x250>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/due.rb
class Due < ActiveRecord::Base

  has_many :rifles
  has_many :archeries
  has_many :barrels
  has_many :miscellaneous
  has_many :optics
  has_many :preloveds
  has_many :reloadings
  has_many :stocks
  has_many :triggers

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/make.rb
class Make < ActiveRecord::Base
  has_many :rifles
  has_many :archeries
  has_many :barrels
  has_many :miscellaneous
  has_many :optics
  has_many :preloveds
  has_many :reloadings
  has_many :stocks
  has_many :triggers

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/miscellaneou.rb
class Miscellaneou < ActiveRecord::Base
  belongs_to :due
  belongs_to :make

  validates :name, presence: true
  validates :name, uniqueness: true

  has_attached_file :image, :styles => { :medium => "450x450>", :thumb => "250x250>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/models/news.rb
class News < ActiveRecord::Base
end

app/models/optic.rb
class Optic < ActiveRecord::Base
  belongs_to :due
  belongs_to :make

  validates :name, presence: true
  validates :name, uniqueness: true

  has_attached_file :image, :styles => { :medium => "450x450>", :thumb => "250x250>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  has_attached_file :image, :styles => { :large => "600x600", :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/preloved.rb
class Preloved < ActiveRecord::Base
  belongs_to :make

  validates :name, presence: true
  validates :name, uniqueness: true

  has_attached_file :image, :styles => { :medium => "450x450>", :thumb => "250x250>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/reloading.rb
class Reloading < ActiveRecord::Base
  belongs_to :due
  belongs_to :make

  validates :name, presence: true
  validates :name, uniqueness: true

  has_attached_file :image, :styles => { :medium => "450x450>", :thumb => "250x250>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/models/rifle.rb
class Rifle < ActiveRecord::Base

  belongs_to :make
  belongs_to :due

  validates :name, presence: true
  validates :name, uniqueness: true

  has_attached_file :image, :styles => { :medium => "450x450>", :thumb => "250x250>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  belongs_to :due
  belongs_to :make

  validates :name, presence: true
  validates :name, uniqueness: true

  has_attached_file :image, :styles => { :medium => "450x450>", :thumb => "250x250>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/models/trigger.rb
class Trigger < ActiveRecord::Base
  belongs_to :due
  belongs_to :make

  validates :name, presence: true
  validates :name, uniqueness: true

  has_attached_file :image, :styles => { :medium => "450x450>", :thumb => "250x250>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/webpage.rb
class Webpage < ActiveRecord::Base
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/when_due.rb
class WhenDue < ActiveRecord::Base

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/optics_controller.rb
class OpticsController < ApplicationController
  before_action :set_optic, only: [:show, :edit, :update, :destroy]

  # GET /optics
  # GET /optics.json
  def index
    @optics = Optic.all
  end

  # GET /optics/1
  # GET /optics/1.json
  def show
  end

  # GET /optics/new
  def new
    @optic = Optic.new
  end

  # GET /optics/1/edit
  def edit
  end

  # POST /optics
  # POST /optics.json
  def create
    @optic = Optic.new(optic_params)

    respond_to do |format|
      if @optic.save
        format.html { redirect_to @optic, notice: 'Optic was successfully created.' }
        format.json { render :show, status: :created, location: @optic }
      else
        format.html { render :new }
        format.json { render json: @optic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /optics/1
  # PATCH/PUT /optics/1.json
  def update
    respond_to do |format|
      if @optic.update(optic_params)
        format.html { redirect_to @optic, notice: 'Optic was successfully updated.' }
        format.json { render :show, status: :ok, location: @optic }
      else
        format.html { render :edit }
        format.json { render json: @optic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /optics/1
  # DELETE /optics/1.json
  def destroy
    @optic.destroy
    respond_to do |format|
      format.html { redirect_to optics_url, notice: 'Optic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_optic
      @optic = Optic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def optic_params
      params.require(:optic).permit(:name, :model, :details, :active, :due_id, :make_id, :image, :mag, :price)
    end
end

app/helpers/dues_helper.rb
module DuesHelper
end

app/helpers/makes_helper.rb
module MakesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/optics_helper.rb
module OpticsHelper
end

app/views/optics/_form.html.erb
<%= simple_form_for @optic, html: {multipart: true} do |f| %>

    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :name %>
      <%= f.input :model %>
      <%= f.association :make %>
      <%= f.input :mag %>
      <%= f.input :price %>
      <%= f.input :details %>
      <%= f.association :due %>
      <%= f.input :image %>
      <%= f.input :active %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, :class => "btn btn-small btn-success" %>
    </div>
<% end %>

app/views/optics/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">


      <h1>Editing Optic</h1>

      <%= render 'form' %>

      <%= link_to 'Show', @optic %> |
      <%= link_to 'Back', optics_path %>

    </div>
    <div class="col-md-2"></div>
  </div>
</div>

app/views/optics/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">

      <p id="notice"><%= notice %></p>

      <h2>Listing Optics</h2>

      <table class="table table-hover table-condensed">
        <thead>
        <tr>
          <th>Name</th>
          <th>Model</th>
          <th>Make</th>
          <th>Mag</th>
          <th>Price</th>
          <th>Due</th>
          <th>Active</th>
          <th colspan="3"></th>
        </tr>
        </thead>

        <tbody>
        <% @optics.each do |optic| %>
            <tr>
              <td><%= optic.name %></td>
              <td><%= optic.model %></td>
              <td><%= optic.make.name %></td>
              <td><%= optic.mag %></td>
              <td><%= number_to_currency(optic.price) %></td>
              <td><%= optic.due.name %></td>
              <td><%= optic.active %></td>
              <td><%= link_to 'Show', optic, :class => "btn btn-small btn-info" %></td>
              <td><%= link_to 'Edit', edit_optic_path(optic), :class => "btn btn-small btn-success" %></td>
              <td><%= link_to 'Destroy', optic, method: :delete, data: {confirm: 'Are you sure?'}, :class => "btn btn-small btn-success" %></td>
            </tr>
        <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New Optic', new_optic_path, :class => "btn btn-small btn-success" %>

    </div>
  </div>
</div>

app/views/optics/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">

      <h2>New Optic</h2>

      <%= render 'form' %>

      <%= link_to 'Back', optics_path %>
    </div>
    <div class="col-md-2"></div>
  </div>
</div>

app/views/optics/show.html.erb
<div class="container">

  <div class="row">
    <div class="col-md-12">
      <h2>
        <strong>
          <%= @optic.name %>
        </strong>
      </h2>
    </div>
  </div>

  <hr>

  <div class="row">

    <div class="col-md-5">

      <p id="notice"><%= notice %></p>

      <p>
        <strong>Model:</strong>
        <%= @optic.model %>
      </p>

      <p>
        <strong>Make:</strong>
        <%= @optic.make.name %>
      </p>

      <p>
        <strong>Mag:</strong>
        <%= @optic.mag %>
      </p>

      <p>
        <strong>Details:</strong>
        <%= @optic.details %>
      </p>

      <p>
        <strong>Due:</strong>
        <%= @optic.due.name %>
      </p>

      <%= link_to 'Back', optics_path %>

    </div>


    <div class="col-md-5">

      <p>
        <%= image_tag @optic.image.url(:medium) %>
      </p>

    </div>

    <%= render 'layouts/sidebar' %>


  </div>

</div>