config/routes.rb
Rails.application.routes.draw do
  resources :stocksproducts
  resources :rifleproducts
  resources :barrelproducts
  resources :opticsproducts
  resources :photos
  resources :static_pages
  resources :webpages
  resources :preloveds
  resources :reloadings
  resources :miscellaneous
  resources :triggers
  resources :archeries
  resources :stocks
  resources :optics
  resources :barrels

  resources :dues
  resources :rifles
  resources :when_dues
  resources :makes
  resources :posts
  resources :news
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/archery.rb
class Archery < ActiveRecord::Base
  belongs_to :due
  belongs_to :make

  validates :name, presence: true
  validates :name, uniqueness: true

  has_attached_file :image, :styles => { :medium => "450x450>", :thumb => "250x250>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/models/barrel.rb
class Barrel < ActiveRecord::Base
  belongs_to :due
  belongs_to :make

  validates :name, presence: true
  validates :name, uniqueness: true

  has_attached_file :image, :styles => { :medium => "450x450>", :thumb => "250x250>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/due.rb
class Due < ActiveRecord::Base

  has_many :rifles
  has_many :archeries
  has_many :barrels
  has_many :miscellaneous
  has_many :optics
  has_many :preloveds
  has_many :reloadings
  has_many :stocks
  has_many :triggers

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/make.rb
class Make < ActiveRecord::Base
  has_many :rifles
  has_many :archeries
  has_many :barrels
  has_many :miscellaneous
  has_many :optics
  has_many :preloveds
  has_many :reloadings
  has_many :stocks
  has_many :triggers

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/miscellaneou.rb
class Miscellaneou < ActiveRecord::Base
  belongs_to :due
  belongs_to :make

  validates :name, presence: true
  validates :name, uniqueness: true

  has_attached_file :image, :styles => { :medium => "450x450>", :thumb => "250x250>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/models/news.rb
class News < ActiveRecord::Base
end

app/models/optic.rb
class Optic < ActiveRecord::Base
  belongs_to :due
  belongs_to :make

  validates :name, presence: true
  validates :name, uniqueness: true

  has_attached_file :image, :styles => { :medium => "450x450>", :thumb => "250x250>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  has_attached_file :image, :styles => { :large => "600x600", :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/preloved.rb
class Preloved < ActiveRecord::Base
  belongs_to :make

  validates :name, presence: true
  validates :name, uniqueness: true

  has_attached_file :image, :styles => { :medium => "450x450>", :thumb => "250x250>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/reloading.rb
class Reloading < ActiveRecord::Base
  belongs_to :due
  belongs_to :make

  validates :name, presence: true
  validates :name, uniqueness: true

  has_attached_file :image, :styles => { :medium => "450x450>", :thumb => "250x250>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/models/rifle.rb
class Rifle < ActiveRecord::Base

  belongs_to :make
  belongs_to :due

  validates :name, presence: true
  validates :name, uniqueness: true

  has_attached_file :image, :styles => { :medium => "450x450>", :thumb => "250x250>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  belongs_to :due
  belongs_to :make

  validates :name, presence: true
  validates :name, uniqueness: true

  has_attached_file :image, :styles => { :medium => "450x450>", :thumb => "250x250>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/models/trigger.rb
class Trigger < ActiveRecord::Base
  belongs_to :due
  belongs_to :make

  validates :name, presence: true
  validates :name, uniqueness: true

  has_attached_file :image, :styles => { :medium => "450x450>", :thumb => "250x250>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/webpage.rb
class Webpage < ActiveRecord::Base
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/when_due.rb
class WhenDue < ActiveRecord::Base

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/miscellaneous_controller.rb
class MiscellaneousController < ApplicationController
  before_action :set_miscellaneou, only: [:show, :edit, :update, :destroy]

  # GET /miscellaneous
  # GET /miscellaneous.json
  def index
    @miscellaneous = Miscellaneou.all
  end

  # GET /miscellaneous/1
  # GET /miscellaneous/1.json
  def show
  end

  # GET /miscellaneous/new
  def new
    @miscellaneou = Miscellaneou.new
  end

  # GET /miscellaneous/1/edit
  def edit
  end

  # POST /miscellaneous
  # POST /miscellaneous.json
  def create
    @miscellaneou = Miscellaneou.new(miscellaneou_params)

    respond_to do |format|
      if @miscellaneou.save
        format.html { redirect_to @miscellaneou, notice: 'Accessory was successfully created.' }
        format.json { render :show, status: :created, location: @miscellaneou }
      else
        format.html { render :new }
        format.json { render json: @miscellaneou.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /miscellaneous/1
  # PATCH/PUT /miscellaneous/1.json
  def update
    respond_to do |format|
      if @miscellaneou.update(miscellaneou_params)
        format.html { redirect_to @miscellaneou, notice: 'Accessory was successfully updated.' }
        format.json { render :show, status: :ok, location: @miscellaneou }
      else
        format.html { render :edit }
        format.json { render json: @miscellaneou.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /miscellaneous/1
  # DELETE /miscellaneous/1.json
  def destroy
    @miscellaneou.destroy
    respond_to do |format|
      format.html { redirect_to miscellaneous_url, notice: 'Accessory was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_miscellaneou
      @miscellaneou = Miscellaneou.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def miscellaneou_params
      params.require(:miscellaneou).permit(:name, :model, :details, :active, :due_id, :make_id, :image, :qty, :price)
    end
end

app/helpers/dues_helper.rb
module DuesHelper
end

app/helpers/makes_helper.rb
module MakesHelper
end

app/helpers/miscellaneous_helper.rb
module MiscellaneousHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/miscellaneous/_form.html.erb
<%= simple_form_for @miscellaneou, html: { multipart: true } do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :model %>
    <%= f.association :make %>
    <%= f.input :details %>
    <%= f.input :qty %>
    <%= f.input :price %>
    <%= f.association :due %>
    <%= f.input :image %>
    <%= f.input :active %>
  </div>

  <div class="form-actions">
    <%= f.submit "Save Accessory", class: "btn btn-small btn-success" %>
  </div>
<% end %>

app/views/miscellaneous/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">

      <h2>Editing Accessories</h2>

      <%= render 'form' %>

      <%= link_to 'Show', @miscellaneou, :class => "btn btn-small btn-info" %>
      <%= link_to 'Back', miscellaneous_path, :class => "btn btn-small btn-info" %>
    </div>
    <div class="col-md-2"></div>
  </div>
</div>

app/views/miscellaneous/index.html.erb
<div class="container">
<div class="row">
  <div class="col-md-12">
    <p id="notice"><%= notice %></p>

    <h1>Listing Accessories</h1>

    <table class="table table-hover table-condensed">
      <thead>
      <tr>
        <th>Name</th>
        <th>Model</th>
        <th>Make</th>
        <th>Quantity</th>
        <th>Price</th>
        <th>Due</th>
        <th>Active</th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @miscellaneous.each do |miscellaneou| %>
          <tr>
            <td><%= miscellaneou.name %></td>
            <td><%= miscellaneou.model %></td>
            <td><%= miscellaneou.make %></td>
            <td><%= miscellaneou.qty %></td>
            <td><%= number_to_currency(miscellaneou.price) %></td>
            <td><%= miscellaneou.due %></td>
            <td><%= miscellaneou.active %></td>
            <td><%= link_to 'Show', miscellaneou %></td>
            <td><%= link_to 'Edit', edit_miscellaneou_path(miscellaneou) %></td>
            <td><%= link_to 'Destroy', miscellaneou, method: :delete, data: {confirm: 'Are you sure?'} %></td>
          </tr>
      <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Accessory', new_miscellaneou_path %>

  </div>
</div>
</div>

app/views/miscellaneous/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">

      <h2>New Accessory</h2>

      <%= render 'form' %>

      <%= link_to 'Back', miscellaneous_path %>

    </div>
    <div class="col-md-2"></div>
  </div>
</div>

app/views/miscellaneous/show.html.erb
<div class="container">

  <div class="row">
    <div class="col-md-12">
      <h2>
        <strong>
          <%= @miscellaneou.name %>
        </strong>
      </h2>
    </div>
  </div>

  <hr>

  <div class="row">
    <div class="col-md-5">

      <p id="notice"><%= notice %></p>

      <p>
        <strong>Model:</strong>
        <%= @miscellaneou.model %>
      </p>

      <p>
        <strong>Make:</strong>
        <%= @miscellaneou.make.name %>
      </p>

      <p>
        <strong>Details:</strong>
        <%= @miscellaneou.details %>
      </p>

      <p>
        <strong>Quantity:</strong>
        <%= @miscellaneou.qty %>
      </p>

      <p>
        <strong>Price:</strong>
        <%= @miscellaneou.price %>
      </p>

      <p>
        <strong>Due:</strong>
        <%= @miscellaneou.due.name %>
      </p>

      <%= link_to 'Back to Accessories', miscellaneou_path, :class => "btn btn-success" %>
    </div>

    <div class="col-md-5">

      <p>
        <%= image_tag @barrel.image.url(:medium) %>
      </p>

    </div>

    <%= render 'layouts/sidebar' %>
    
  </div>