config/routes.rb
Rails.application.routes.draw do
  resources :stocksproducts
  resources :rifleproducts
  resources :barrelproducts
  resources :opticsproducts
  resources :photos
  resources :static_pages
  resources :webpages
  resources :preloveds
  resources :reloadings
  resources :miscellaneous
  resources :triggers
  resources :archeries
  resources :stocks
  resources :optics
  resources :barrels

  resources :dues
  resources :rifles
  resources :when_dues
  resources :makes
  resources :posts
  resources :news
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/archery.rb
class Archery < ActiveRecord::Base
  belongs_to :due
  belongs_to :make

  validates :name, presence: true
  validates :name, uniqueness: true

  has_attached_file :image, :styles => { :medium => "450x450>", :thumb => "250x250>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/models/barrel.rb
class Barrel < ActiveRecord::Base
  belongs_to :due
  belongs_to :make

  validates :name, presence: true
  validates :name, uniqueness: true

  has_attached_file :image, :styles => { :medium => "450x450>", :thumb => "250x250>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/due.rb
class Due < ActiveRecord::Base

  has_many :rifles
  has_many :archeries
  has_many :barrels
  has_many :miscellaneous
  has_many :optics
  has_many :preloveds
  has_many :reloadings
  has_many :stocks
  has_many :triggers

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/make.rb
class Make < ActiveRecord::Base
  has_many :rifles
  has_many :archeries
  has_many :barrels
  has_many :miscellaneous
  has_many :optics
  has_many :preloveds
  has_many :reloadings
  has_many :stocks
  has_many :triggers

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/miscellaneou.rb
class Miscellaneou < ActiveRecord::Base
  belongs_to :due
  belongs_to :make

  validates :name, presence: true
  validates :name, uniqueness: true

  has_attached_file :image, :styles => { :medium => "450x450>", :thumb => "250x250>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/models/news.rb
class News < ActiveRecord::Base
end

app/models/optic.rb
class Optic < ActiveRecord::Base
  belongs_to :due
  belongs_to :make

  validates :name, presence: true
  validates :name, uniqueness: true

  has_attached_file :image, :styles => { :medium => "450x450>", :thumb => "250x250>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  has_attached_file :image, :styles => { :large => "600x600", :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/preloved.rb
class Preloved < ActiveRecord::Base
  belongs_to :make

  validates :name, presence: true
  validates :name, uniqueness: true

  has_attached_file :image, :styles => { :medium => "450x450>", :thumb => "250x250>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/reloading.rb
class Reloading < ActiveRecord::Base
  belongs_to :due
  belongs_to :make

  validates :name, presence: true
  validates :name, uniqueness: true

  has_attached_file :image, :styles => { :medium => "450x450>", :thumb => "250x250>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/models/rifle.rb
class Rifle < ActiveRecord::Base

  belongs_to :make
  belongs_to :due

  validates :name, presence: true
  validates :name, uniqueness: true

  has_attached_file :image, :styles => { :medium => "450x450>", :thumb => "250x250>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  belongs_to :due
  belongs_to :make

  validates :name, presence: true
  validates :name, uniqueness: true

  has_attached_file :image, :styles => { :medium => "450x450>", :thumb => "250x250>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/models/trigger.rb
class Trigger < ActiveRecord::Base
  belongs_to :due
  belongs_to :make

  validates :name, presence: true
  validates :name, uniqueness: true

  has_attached_file :image, :styles => { :medium => "450x450>", :thumb => "250x250>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/webpage.rb
class Webpage < ActiveRecord::Base
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/when_due.rb
class WhenDue < ActiveRecord::Base

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/rifles_controller.rb
class RiflesController < ApplicationController
  before_action :set_rifle, only: [:show, :edit, :update, :destroy]

  # GET /rifles
  # GET /rifles.json
  def index
    @rifles = Rifle.all
  end

  # GET /rifles/1
  # GET /rifles/1.json
  def show
    @details = Redcarpet::Markdown.new(Redcarpet::Render::HTML).render(@rifle.details)
  end

  # GET /rifles/new
  def new
    @rifle = Rifle.new
  end

  # GET /rifles/1/edit
  def edit
  end

  # POST /rifles
  # POST /rifles.json
  def create
    @rifle = Rifle.new(rifle_params)

    respond_to do |format|
      if @rifle.save
        format.html { redirect_to @rifle, notice: 'Rifle was successfully created.' }
        format.json { render :show, status: :created, location: @rifle }
      else
        format.html { render :new }
        format.json { render json: @rifle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rifles/1
  # PATCH/PUT /rifles/1.json
  def update
    respond_to do |format|
      if @rifle.update(rifle_params)
        format.html { redirect_to @rifle, notice: 'Rifle was successfully updated.' }
        format.json { render :show, status: :ok, location: @rifle }
      else
        format.html { render :edit }
        format.json { render json: @rifle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rifles/1
  # DELETE /rifles/1.json
  def destroy
    @rifle.destroy
    respond_to do |format|
      format.html { redirect_to rifles_url, notice: 'Rifle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rifle
      @rifle = Rifle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rifle_params
      params.require(:rifle).permit(:name, :model, :bore, :details, :active, :make_id, :due_id, :image, :price, :style)
    end
end

app/helpers/dues_helper.rb
module DuesHelper
end

app/helpers/makes_helper.rb
module MakesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/rifles_helper.rb
module RiflesHelper
end

app/views/rifles/_form.html.erb
<%= simple_form_for @rifle, html: { multipart: true } do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.association :make %>
    <%= f.input :model %>
    <%= f.input :style %>
    <%= f.input :bore, label: 'Calibre' %>
    <%= f.input :price %>
    <%= f.association :due %>
    <%= f.input :details %>
    <%= f.input :active %>
    <%= f.input :image %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => "btn btn-small btn-success" %>
  </div>
<% end %>

app/views/rifles/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">

      <h1>Editing Rifle</h1>

      <%= render 'form' %>

      <%= link_to 'Show', @rifle %> |
      <%= link_to 'Back', rifles_path %>

    </div>
    <div class="col-md-2"></div>
  </div>
</div>

app/views/rifles/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">

      <p id="notice"><%= notice %></p>

      <h1>Listing Rifles & Actions</h1>

      <table class="table table-hover table-condensed">
        <thead>
        <tr>
          <th>Name</th>
          <th>Make</th>
          <th>Model</th>
          <th>Style</th>
          <th>Calibre</th>
          <th>Price</th>
          <th>Due</th>
          <th>Active</th>
          <th colspan="3"></th>
        </tr>
        </thead>

        <tbody>
        <% @rifles.each do |rifle| %>
            <tr>
              <td><%= rifle.name %></td>
              <td><%= rifle.make.name %></td>
              <td><%= rifle.model %></td>
              <td><%= rifle.style %></td>
              <td><%= rifle.bore %></td>
              <td><%= number_to_currency(rifle.price) %></td>
              <td><%= rifle.due.name %></td>
              <td><%= rifle.active %></td>
              <td><%= link_to 'Show', rifle, :class => "btn btn-small btn-info" %></td>
              <td><%= link_to 'Edit', edit_rifle_path(rifle), :class => "btn btn-small btn-success" %></td>
              <td><%= link_to 'Delete', rifle, method: :delete, data: {confirm: 'Are you sure?'}, :class => "btn btn-xs btn-danger" %></td>
            </tr>
        <% end %>
        </tbody>
      </table>

      <br>
      <hr>
      <%= link_to 'New Rifle', new_rifle_path, :class => "btn btn-small btn-success" %>

    </div>
  </div>
</div>

app/views/rifles/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">

      <h1>New Rifle</h1>

      <%= render 'form' %>

      <%= link_to 'Back', rifles_path %>

    </div>
    <div class="col-md-2"></div>
  </div>
</div>

app/views/rifles/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h2>
        <strong>
          <%= @rifle.name %>
        </strong>
      </h2>
    </div>
  </div>
  <hr>
  <div class="row">
    <div class="col-md-5">

      <p>
        <strong>Model:</strong>
        <%= @rifle.model %>
      </p>

      <p>
        <strong>Make:</strong>
        <%= @rifle.make.name %>
      </p>

      <p>
        <strong>Style:</strong>
        <%= @rifle.style %>
      </p>
      <p>
        <strong>Calibre:</strong>
        <%= @rifle.bore %>
      </p>

      <p>
        <strong>Price:</strong>
        <%= number_to_currency(@rifle.price) %>
      </p>


      <p>
        <strong>Availability:</strong>
        <%= @rifle.due.name %>
      </p>
      <hr>
      <p>
        <%= markdown(@rifle.details) %>
      </p>

      <hr>
      <%= link_to 'Back to Rifles and Actions', rifleproducts_path, :class => "btn btn-success" %>

    </div>

    <div class="col-md-5">
      <p><%#= image_tag @rifle.image.url(:medium) %></p>
    </div
    <div class="col-md-2">
      <%= render 'layouts/sidebar' %>
    </div>

  </div>
</div>